#!/bin/sh

printf "Updating MIME types..."
xdg-mime default photoinsight.desktop image/bmp 
xdg-mime default photoinsight.desktop image/x-cut 
xdg-mime default photoinsight.desktop image/x-dds 
xdg-mime default photoinsight.desktop image/x-exr 
xdg-mime default photoinsight.desktop image/fax-g3 
xdg-mime default photoinsight.desktop image/gif 
xdg-mime default photoinsight.desktop image/vnd.radiance 
xdg-mime default photoinsight.desktop image/vnd.microsoft.icon 
xdg-mime default photoinsight.desktop image/x-iff 
xdg-mime default photoinsight.desktop image/j2k 
xdg-mime default photoinsight.desktop image/x-mng 
xdg-mime default photoinsight.desktop image/jp2 
xdg-mime default photoinsight.desktop image/jpeg 
xdg-mime default photoinsight.desktop image/vnd.ms-photo 
xdg-mime default photoinsight.desktop image/x-koala 
xdg-mime default photoinsight.desktop video/x-mng 
xdg-mime default photoinsight.desktop image/freeimage-pnm 
xdg-mime default photoinsight.desktop image/freeimage-pnm 
xdg-mime default photoinsight.desktop image/x-photo-cd 
xdg-mime default photoinsight.desktop image/x-pcx 
xdg-mime default photoinsight.desktop image/x-portable-floatmap 
xdg-mime default photoinsight.desktop image/freeimage-pnm 
xdg-mime default photoinsight.desktop image/freeimage-pnm 
xdg-mime default photoinsight.desktop image/x-pict 
xdg-mime default photoinsight.desktop image/png 
xdg-mime default photoinsight.desktop image/freeimage-pnm 
xdg-mime default photoinsight.desktop image/freeimage-pnm 
xdg-mime default photoinsight.desktop image/vnd.adobe.photoshop 
xdg-mime default photoinsight.desktop image/x-cmu-raster 
xdg-mime default photoinsight.desktop image/x-dcraw 
xdg-mime default photoinsight.desktop image/x-sgi 
xdg-mime default photoinsight.desktop image/x-tga 
xdg-mime default photoinsight.desktop image/tiff 
xdg-mime default photoinsight.desktop image/vnd.wap.wbmp 
xdg-mime default photoinsight.desktop image/webp 
xdg-mime default photoinsight.desktop image/x-xbitmap 
xdg-mime default photoinsight.desktop image/x-xpixmap 
printf "DONE\n"